name: WC - Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: pipenv install
    
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: pipenv run test